project: tumor
mode: one_shot
classification_type: binary

data:
  train_csv: "data/tumor/tumor_dataset.csv"
  test_csv: "data/tumor/tumor_test_dataset.csv"
  save_path: ./results/${project}/${classification_type}/${mode}/
  num_shots: 5
  batch_size: 1
  randomize_few_shot: false
  seed: 40
  num_test_images: 16
  randomize_test_images: true
  test_seed: 40
  labels_path: "data/tumor/test/labels.json"

model:
  model_name: gemini-2.0-flash
  model_kwargs:
    temperature: 0.7
    top_p: 0.95
    max_output_tokens: 1024

user_args:
  prompt_path: "./prompts/tumor/few_shot.txt"
  verbose: true
  debug: false

classification:
  type: ${classification_type}
  labels: ["Tumor", "No Tumor"]