project: Tumor
mode: one_shot

data:
  image_root: ./data/tumor/
  test_labels_json: ./data/tumor/test_labels.json
  save_path: ./results/${project}/${mode}/
  num_shots: 1
  batch_size: 1
  randomize_few_shot: true
  seed: 42

model:
  model_name: gemini-2.0-flash
  model_kwargs:
    temperature: 0.7
    top_p: 0.95
    max_output_tokens: 1024

user_args:
  prompt_path: ./prompts/tumor/few_shot.txt
  verbose: true
  debug: false