project: tumor
mode: one_shot

data:
  train_csv: "data/tumor/tumor_dataset.csv"
  test_csv: "data/tumor/tumor_test_dataset.csv"
  save_path: ./results/${project}/${mode}/
  num_shots: 2
  batch_size: 1
  randomize_few_shot: false
  seed: 42
  num_test_images: 4
  randomize_test_images: true
  test_seed: 42
  # Specify the path to the ground-truth labels file (adjust as needed)
  labels_path: "data/tumor/test/labels.json"

model:
  model_name: gemini-2.0-flash
  model_kwargs:
    temperature: 0.7
    top_p: 0.95
    max_output_tokens: 1024

user_args:
  prompt_path: "./prompts/tumor/few_shot.txt"
  verbose: true
  debug: false

classification:
  type: binary
  labels: ["Tumor", "No Tumor"]