project: CRC100K
mode: one_shot

data:
  train_csv: "data/CRC100K/binary/CRC100K_dataset.csv"      # CSV for positive/negative
  test_csv: "data/CRC100K/binary/CRC100K_test_dataset.csv"  # CSV for the test set
  save_path: ./results/${project}/${mode}/
  num_shots: 1
  batch_size: 1
  randomize_few_shot: false
  seed: 42
  num_test_images: 2  # how many test images to process
  randomize_test_images: true     # NEW
  test_seed: 42            


model:
  model_name: gemini-2.0-flash
  model_kwargs:
    temperature: 0.7
    top_p: 0.95
    max_output_tokens: 1024

user_args:
  prompt_path: ./prompts/CRC100K/binary/few_shot.txt
  verbose: true
  debug: false