name: icl2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pillow
  - imageio
  - scikit-image
  - nibabel
  - statsmodels
  - jupyter
  - ipykernel
  - tqdm
  - pytz
  - pyyaml
  - regex
  - six
  - networkx
  - typer
  - rich
  - sentencepiece
  - torch
  - torchvision
  - torchaudio
  - transformers
  - fastapi
  - uvicorn
  - httpx
  - grpcio
  - google-auth
  - google-api-python-client
  - google-cloud-storage
  - google-cloud-core
  - google-cloud-bigquery
  - google-cloud-aiplatform
  - google-cloud-resource-manager
  - protobuf
  - pyarrow
  - pyparsing
  - patsy
  - jinja2
  - markdown-it-py
  - mpmath
  - sympy
  - wrapt
  - pywavelets
  - humanize
  - joblib
  - decorator
  - traitlets
  - psutil
  - filelock
  - zipp
  - packaging
  - typing-extensions
  - uvloop
  - watchfiles
  - httptools
  - starlette
  - grpcio-status
  - rsa
  - uritemplate
  - charset-normalizer
  - idna
  - urllib3
  - certifi
  - click
  - python-dotenv
  - dotmap
  - tree
  - shapely
  - timm
  - accelerate
  - einops
  - faiss-cpu
  - docopt
  - svgwrite
  - shellingham
  - nest-asyncio
  - prompt-toolkit
  - pygments
  - tornado
  - tifffile
  - xarray
  - libtiff
  - jpeg
  - cmake  # needed for some wheel builds
  - pip:
      - bitsandbytes==0.43.1
      - huggingface-hub==0.33.4
      - google-genai==1.20.0
      - google-generativeai==0.8.5
      - google-ai-generativelanguage==0.6.15
      - simpleitk
      - git+https://github.com/Radiomics/pyradiomics.git@8ed579383b44806651c463d5e691f3b2b57522ab