name: icl
channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.10
  - ipython
  - ipykernel
  - jupyter_client
  - jupyter_core
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - seaborn
  - sentencepiece
  - sentencepiece-python
  - simpleitk
  - psutil
  - traitlets
  - tornado
  - typing_extensions
  - pip
  - pip:
      - accelerate==1.9.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - bitsandbytes==0.43.1
      - cachetools==5.5.2
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.2
      - cycler==0.12.1
      - deprecated==1.2.18
      - docopt==0.6.2
      - docstring-parser==0.16
      - dotenv==0.9.9
      - einops==0.8.1
      - faiss-cpu==1.11.0
      - fastapi==0.115.13
      - filelock==3.18.0
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.0rc0
      - google-api-python-client==2.168.0
      - google-auth==2.39.0
      - google-auth-httplib2==0.2.0
      - google-cloud-aiplatform==1.97.0
      - google-cloud-bigquery==3.34.0
      - google-cloud-core==2.4.3
      - google-cloud-resource-manager==1.14.2
      - google-cloud-storage==2.19.0
      - google-crc32c==1.7.1
      - google-genai==1.20.0
      - google-generativeai==0.8.5
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - grpc-google-iam-v1==0.14.2
      - grpcio==1.71.0
      - grpcio-status==1.71.0
      - h11==0.16.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.33.4
      - humanize==4.12.3
      - idna==3.10
      - imageio==2.37.0
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - nibabel==5.3.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - packaging==25.0
      - pillow==11.2.1
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pygments==2.19.1
      - pykwalify==1.8.0
      - pyparsing==3.2.3
      - git+https://github.com/Radiomics/pyradiomics.git@master
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - rsa==4.9.1
      - ruamel-yaml==0.18.12
      - ruamel-yaml-clib==0.2.12
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - shapely==2.1.1
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.46.2
      - svgwrite==1.4.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.6.11
      - timm==1.0.15
      - tokenizers==0.21.1
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchio==0.20.8
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.53.3
      - tree==0.2.4
      - triton==3.3.1
      - typer==0.15.4
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uritemplate==4.1.1
      - urllib3==2.4.0
      - uvicorn==0.34.3
      - uvloop==0.21.0
      - watchfiles==1.1.0
      - websockets==15.0.1
      - wrapt==1.17.2