project: glioma
mode: three_shot
classification_type: binary
modality: t1

data:
  train_csv: "data/glioma/binary/t1/glioma_dataset.csv"
  test_csv: "data/glioma/binary/t1/glioma_test_dataset.csv"
  save_path: ./results/${project}/${classification_type}/${mode}/${modality}/
  num_shots: 5
  batch_size: 1
  randomize_few_shot: false
  seed: 40
  num_test_images: 26
  randomize_test_images: true
  test_seed: 40
  labels_path: "data/glioma/binary/t1/labels.json"

model:
  backend: llava_hf
  model_name: llava-hf/llava-1.5-7b-hf
  model_kwargs:
    temperature: 0.0
    top_p: 0.95
    max_output_tokens: 1024

user_args:
  prompt_path: "./prompts/glioma/binary/t1/few_shot.txt"
  verbose: true
  debug: false

classification:
  type: ${classification_type}
  labels: ["class1", "class2"]
