project: glioma
mode: three_shot
classification_type: binary
modality: t2

data:
  train_csv: "data/glioma/binary/t2/glioma_dataset.csv"
  test_csv: "data/glioma/binary/t2/glioma_test_dataset.csv"
  save_path: ./results/${project}/${classification_type}/${mode}/${modality}/
  num_shots: 3
  batch_size: 1
  randomize_few_shot: false
  seed: 42
  num_test_images: 24
  randomize_test_images: true
  test_seed: 40
  labels_path: "data/glioma/binary/t2/labels.json"

model:
  model_name: gemini-2.0-flash
  model_kwargs:
    temperature: 0
    top_p: 1.0
    max_output_tokens: 1024

user_args:
  prompt_path: "./prompts/glioma/binary/t2/few_shot.txt"
  verbose: true
  debug: false

classification:
  type: ${classification_type}
  labels: ["class1", "class2"]

sampling:
  strategy: knn          # <- tells the sampler to use KNN
  knn_csv: null          # null ⇒ build neighbours at run-time
  num_neighbors: 2       # = num_shots - 1   (example: 3-shot)
  anchors:
    class1: "/home/tim/ICL-VL/data/glioma/png_T2/UCSF-PDGM-0439_T2_bias.nii/UCSF-PDGM-0439_T2_bias.nii_z097_same_rgb.png"
    class2: "/home/tim/ICL-VL/data/glioma/png_T2/UCSF-PDGM-0010_T2_bias.nii/UCSF-PDGM-0010_T2_bias.nii_z079_same_rgb.png"
  embedder: resnet50
  device: cuda:0         # "cpu" if no GPU
