# ------------------------------------------------------------------ #
# Project & mode
# ------------------------------------------------------------------ #
project: CRC100K
mode:    three_shot           # 3 examples per label
classification_type: binary   # "Tumor" vs "No Tumor"

# ------------------------------------------------------------------ #
# Data paths
# ------------------------------------------------------------------ #
data:
  train_csv:   "data/CRC100K/binary/CRC100K_dataset.csv"
  test_csv:    "data/CRC100K/binary/CRC100K_test_dataset.csv"
  save_path:   ./results/${project}/${classification_type}/${mode}/

  num_shots:   3              # ← three-shot
  batch_size:  1

  randomize_few_shot: true    # shuffle available indices
  seed:        40             # change → new random few-shot set

  num_test_images:      40
  randomize_test_images: true
  test_seed:            1

  labels_path: "data/CRC100K/binary/labels.json"

# ------------------------------------------------------------------ #
# Few-shot sampling strategy
# ------------------------------------------------------------------ #
sampling:
  strategy: random            # ← classic random sampling (default)

# ------------------------------------------------------------------ #
# Model settings
# ------------------------------------------------------------------ #
model:
  model_name: gemini-2.0-flash
  model_kwargs:
    temperature:       0.7
    top_p:             0.95
    max_output_tokens: 1024

# ------------------------------------------------------------------ #
# Prompt, verbosity, etc.
# ------------------------------------------------------------------ #
user_args:
  prompt_path: "./prompts/CRC100K/binary/few_shot.txt"
  verbose:     true
  debug:       false

# ------------------------------------------------------------------ #
# Classification label mapping (redundant but explicit)
# ------------------------------------------------------------------ #
classification:
  type:   ${classification_type}
  labels: ["Tumor", "No Tumor"]

# ------------------------------------------------------------------ #
# Retrieval / embedding configuration (unchanged)
# ------------------------------------------------------------------ #
retrieval:
  enable:           true
  index_path:       embeddings/CRC100K_binary_dinov2_224.faiss
  meta_path:        embeddings/CRC100K_binary_dinov2_224.faiss.meta.npy
  model_name:       vit_small_patch14_dinov2
  img_size:         224            # must match embedding size
  overquery_factor: 5