# ------------------------------------------------------------------ #
# Project & mode
# ------------------------------------------------------------------ #
project: CRC100K
mode:    three_shot_knn        # distinguish this run
classification_type: binary

# ------------------------------------------------------------------ #
# Data paths
# ------------------------------------------------------------------ #
data:
  train_csv:   "data/CRC100K/binary/CRC100K_dataset.csv"
  test_csv:    "data/CRC100K/binary/CRC100K_test_dataset.csv"
  save_path:   ./results/${project}/${classification_type}/${mode}/

  num_shots:   3              # anchor + 2 neighbours
  batch_size:  1

  seed:        40             # controls *anchor* pick and random ops
  randomize_few_shot: false   # N/A for KNN (kept for symmetry)

  num_test_images:      40
  randomize_test_images: true
  test_seed:            1

  labels_path: "data/CRC100K/binary/labels.json"

# ------------------------------------------------------------------ #
# Few-shot sampling strategy
# ------------------------------------------------------------------ #
sampling:
  strategy:       knn
  knn_csv:        data/knn_31_similar.csv   # neighbour table you built
  num_neighbors:  2                         # anchor + 2 nn = 3-shot
  anchors:
    Tumor:    random                        # choose a valid anchor each run
    No Tumor: random                        # (change seed to vary)

# ------------------------------------------------------------------ #
# Model settings
# ------------------------------------------------------------------ #
model:
  model_name: gemini-2.0-flash
  model_kwargs:
    temperature:       0.7
    top_p:             0.95
    max_output_tokens: 1024

# ------------------------------------------------------------------ #
# Prompt, verbosity, etc.
# ------------------------------------------------------------------ #
user_args:
  prompt_path: "./prompts/CRC100K/binary/few_shot.txt"
  verbose:     true
  debug:       false

# ------------------------------------------------------------------ #
# Classification label mapping
# ------------------------------------------------------------------ #
classification:
  type:   ${classification_type}
  labels: ["Tumor", "No Tumor"]

# ------------------------------------------------------------------ #
# Retrieval / embedding configuration
# ------------------------------------------------------------------ #
retrieval:
  enable:           true
  index_path:       embeddings/CRC100K_binary_dinov2_224.faiss
  meta_path:        embeddings/CRC100K_binary_dinov2_224.faiss.meta.npy
  model_name:       vit_small_patch14_dinov2
  img_size:         224
  overquery_factor: 5